project:
  type: website

resources:
  - CNAME

website:
  title: "Ryan R. Bart"
  site-url: https://ryanrbart.com
  description: "Ryan R. Bart"
  favicon: img/favicon.png
  open-graph: true

format:
  html:
    theme: simplex
    css: styles.css

